version: '3.9'

services:
  store-gateway:
    build:
      context: .
      dockerfile: ./apps/store-gateway/Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start:dev store-gateway
    depends_on:
      - products

  products:
    build:
      context: .
      dockerfile: ./apps/products/Dockerfile.dev
    ports:
      - '4000:4000'
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start:dev products
  products-db:
    image: mysql:9.4
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '${DB_PORT}:${DB_PORT}'
  adminer:
    image: adminer
    depends_on:
      - products-db
    ports:
      - '8080:8080'
